name: Test 
on: 
  push:
    branches: [ "main" ]


jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
    - name: Git Clone
      uses: actions/checkout@v5

    - name: Run ls command
      run: ls -la
